/**
 * Quilt Block & Layout Overlay Registry
 *
 * Maps block and layout names to their SVG overlay files in /quilt_blocks/ and /quilt_layouts/.
 * All block SVGs use a 300×300 viewBox with filled patches.
 * Layout SVGs use proportional viewBoxes at 10px/inch with structural data-role attributes.
 * Layouts are fixed-aspect-ratio worktables: resizable but always maintain proportions.
 */

export interface BlockOverlay {
  id: string;
  name: string;
  displayName: string;
  svgPath: string;
  commonSizes: string[];
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  gridUnits: number;
}

export interface LayoutOverlay {
  id: string;
  name: string;
  displayName: string;
  svgPath: string;
  dimensions: { width: number; height: number };
  description: string;
  blockLayout?: { cols: number; rows: number };
}

export const BLOCK_OVERLAYS: BlockOverlay[] = [
  {
    id: 'nine-patch',
    name: 'nine_patch',
    displayName: 'Nine Patch',
    svgPath: '/quilt_blocks/01_nine_patch.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9 squares in a 3×3 grid — the most fundamental quilt block',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'churn-dash',
    name: 'churn_dash',
    displayName: 'Churn Dash',
    svgPath: '/quilt_blocks/02_churn_dash.svg',
    commonSizes: ['3"', '4.5"', '6"', '7.5"', '9"'],
    description: '4 HSTs and 4 rectangles around a center square, resembling a butter churn',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'log-cabin',
    name: 'log_cabin',
    displayName: 'Log Cabin',
    svgPath: '/quilt_blocks/03_log_cabin.svg',
    commonSizes: ['6"', '8"', '12"'],
    description: 'Concentric strips around a central square, mimicking log cabin construction',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'ohio-star',
    name: 'ohio_star',
    displayName: 'Ohio Star',
    svgPath: '/quilt_blocks/04_ohio_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Classic 8-pointed star in a 9-patch layout using quarter-square triangles',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'bear-paw',
    name: 'bear_paw',
    displayName: 'Bear Paw',
    svgPath: '/quilt_blocks/05_bear_paw.svg',
    commonSizes: ['12"'],
    description: 'Squares and HSTs forming a bear paw shape with distinct claws',
    difficulty: 'intermediate',
    gridUnits: 7,
  },
  {
    id: 'pinwheel',
    name: 'pinwheel',
    displayName: 'Pinwheel',
    svgPath: '/quilt_blocks/06_pinwheel.svg',
    commonSizes: ['3"', '4"', '5"', '6"', '8"'],
    description: '4 HSTs rotating around a center point creating a spinning effect',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'flying-geese',
    name: 'flying_geese',
    displayName: 'Flying Geese',
    svgPath: '/quilt_blocks/07_flying_geese.svg',
    commonSizes: ['2"×4"', '3"×6"'],
    description:
      'Rectangular block with a center triangle and two side triangles (width = 2× height)',
    difficulty: 'beginner',
    gridUnits: 6,
  },
  {
    id: 'drunkards-path',
    name: 'drunkards_path',
    displayName: "Drunkard's Path",
    svgPath: '/quilt_blocks/08_drunkards_path.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Quarter circle set in a square — great introduction to curved piecing',
    difficulty: 'advanced',
    gridUnits: 2,
  },
  {
    id: 'shoo-fly',
    name: 'shoo_fly',
    displayName: 'Shoo Fly',
    svgPath: '/quilt_blocks/09_shoo_fly.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with 4 HSTs and 4 squares around a center square',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'sawtooth-star',
    name: 'sawtooth_star',
    displayName: 'Sawtooth Star',
    svgPath: '/quilt_blocks/10_sawtooth_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '8-pointed star constructed from flying geese around a center square',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'friendship-star',
    name: 'friendship_star',
    displayName: 'Friendship Star',
    svgPath: '/quilt_blocks/11_friendship_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with HSTs arranged to form a four-pointed star',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'square-in-square',
    name: 'square_in_square',
    displayName: 'Square in a Square',
    svgPath: '/quilt_blocks/12_square_in_square.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Central square surrounded by 4 triangles creating a diamond illusion',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'rail-fence',
    name: 'rail_fence',
    displayName: 'Rail Fence',
    svgPath: '/quilt_blocks/13_rail_fence.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Simple striped square block — versatile for many layouts',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'card-trick',
    name: 'card_trick',
    displayName: 'Card Trick',
    svgPath: '/quilt_blocks/14_card_trick.svg',
    commonSizes: ['4.5"', '6"', '9"', '12"'],
    description: 'HST arrangement resembling playing cards in a 9-patch',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'double-star',
    name: 'double_star',
    displayName: 'Double Star',
    svgPath: '/quilt_blocks/15_double_star.svg',
    commonSizes: ['7.5"', '10"', '12.5"', '15"'],
    description: 'Layered star design with inner and outer star points',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'lone-star',
    name: 'lone_star',
    displayName: 'Lone Star',
    svgPath: '/quilt_blocks/16_lone_star.svg',
    commonSizes: ['12"+'],
    description:
      '8-pointed diamond star radiating from center — often used as a single-block quilt',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'tumbling-blocks',
    name: 'tumbling_blocks',
    displayName: 'Tumbling Blocks',
    svgPath: '/quilt_blocks/17_tumbling_blocks.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '3D cube illusion created with diamonds and careful color placement',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'dresden-plate',
    name: 'dresden_plate',
    displayName: 'Dresden Plate',
    svgPath: '/quilt_blocks/18_dresden_plate.svg',
    commonSizes: ['12"+'],
    description: 'Circular petal design with radiating wedges around a center circle',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'irish-chain',
    name: 'irish_chain',
    displayName: 'Irish Chain',
    svgPath: '/quilt_blocks/19_irish_chain.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch blocks and solid squares forming diagonal chain patterns',
    difficulty: 'beginner',
    gridUnits: 5,
  },
  {
    id: 'hst',
    name: 'hst',
    displayName: 'Half-Square Triangle',
    svgPath: '/quilt_blocks/20_hst.svg',
    commonSizes: ['2"', '3"', '4"', '6"', '8"', '12"'],
    description: 'Two triangles forming a square — the most versatile building block in quilting',
    difficulty: 'beginner',
    gridUnits: 1,
  },
  {
    id: 'anvil',
    name: 'anvil',
    displayName: 'Anvil',
    svgPath: '/quilt_blocks/21_anvil.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Anvil-shaped triangles and squares',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'album',
    name: 'album',
    displayName: 'Album',
    svgPath: '/quilt_blocks/22_album.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Framed picture-style block',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'annies-choice',
    name: 'annies_choice',
    displayName: "Annie's Choice",
    svgPath: '/quilt_blocks/23_annies_choice.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Star with crossed bands',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'antique-tile',
    name: 'antique_tile',
    displayName: 'Antique Tile',
    svgPath: '/quilt_blocks/24_antique_tile.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Tile-like geometric repeat',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'arkansas-traveller',
    name: 'arkansas_traveller',
    displayName: 'Arkansas Traveller',
    svgPath: '/quilt_blocks/25_arkansas_traveller.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Curved path with triangles',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'attic-windows',
    name: 'attic_windows',
    displayName: 'Attic Windows',
    svgPath: '/quilt_blocks/26_attic_windows.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '3D window frame illusion',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'basket',
    name: 'basket',
    displayName: 'Basket',
    svgPath: '/quilt_blocks/27_basket.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Woven basket with handle',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'bear-track',
    name: 'bear_track',
    displayName: 'Bear Track',
    svgPath: '/quilt_blocks/28_bear_track.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Smaller paw print variation',
    difficulty: 'intermediate',
    gridUnits: 5,
  },
  {
    id: 'birds-in-the-air',
    name: 'birds_in_the_air',
    displayName: 'Birds in the Air',
    svgPath: '/quilt_blocks/29_birds_in_the_air.svg',
    commonSizes: ['3"', '6"', '9"'],
    description: 'Flying bird triangles',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'bow-tie',
    name: 'bow_tie',
    displayName: 'Bow Tie',
    svgPath: '/quilt_blocks/30_bow_tie.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Bow shape with squares',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'broken-dishes',
    name: 'broken_dishes',
    displayName: 'Broken Dishes',
    svgPath: '/quilt_blocks/31_broken_dishes.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Random triangle shards',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'broken-pinwheel',
    name: 'broken_pinwheel',
    displayName: 'Broken Pinwheel',
    svgPath: '/quilt_blocks/32_broken_pinwheel.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Pinwheel with offset arms',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'carpenters-wheel',
    name: 'carpenters_wheel',
    displayName: "Carpenter's Wheel",
    svgPath: '/quilt_blocks/33_carpenters_wheel.svg',
    commonSizes: ['12"+'],
    description: 'Large spoked wheel star',
    difficulty: 'advanced',
    gridUnits: 5,
  },
  {
    id: 'cathedral-window',
    name: 'cathedral_window',
    displayName: 'Cathedral Window',
    svgPath: '/quilt_blocks/34_cathedral_window.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Folded fabric "window"',
    difficulty: 'advanced',
    gridUnits: 3,
  },
  {
    id: 'chevron',
    name: 'chevron',
    displayName: 'Chevron',
    svgPath: '/quilt_blocks/35_chevron.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Zigzag stripe effect',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'corn-and-beans',
    name: 'corn_and_beans',
    displayName: 'Corn and Beans',
    svgPath: '/quilt_blocks/36_corn_and_beans.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Farm motif with kernels',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'courthouse-steps',
    name: 'courthouse_steps',
    displayName: 'Courthouse Steps',
    svgPath: '/quilt_blocks/37_courthouse_steps.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Log Cabin concentric variation',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'cross-and-crown',
    name: 'cross_and_crown',
    displayName: 'Cross and Crown',
    svgPath: '/quilt_blocks/38_cross_and_crown.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Cross with crown points',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'delectable-mountains',
    name: 'delectable_mountains',
    displayName: 'Delectable Mountains',
    svgPath: '/quilt_blocks/39_delectable_mountains.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Mountain peak triangles',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'double-pinwheel',
    name: 'double_pinwheel',
    displayName: 'Double Pinwheel',
    svgPath: '/quilt_blocks/40_double_pinwheel.svg',
    commonSizes: ['6"', '8"', '12"'],
    description: 'Two layered rotating HSTs',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'dutchmans-puzzle',
    name: 'dutchmans_puzzle',
    displayName: "Dutchman's Puzzle",
    svgPath: '/quilt_blocks/41_dutchmans_puzzle.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Flying geese puzzle layout',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'economy-block',
    name: 'economy_block',
    displayName: 'Economy Block',
    svgPath: '/quilt_blocks/42_economy_block.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Square-in-square (diamond)',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'evening-star',
    name: 'evening_star',
    displayName: 'Evening Star',
    svgPath: '/quilt_blocks/43_evening_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Star with alternating points',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'four-patch',
    name: 'four_patch',
    displayName: 'Four Patch',
    svgPath: '/quilt_blocks/44_four_patch.svg',
    commonSizes: ['3"', '6"', '9"'],
    description: 'Basic 2×2 grid',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'grandmothers-fan',
    name: 'grandmothers_fan',
    displayName: "Grandmother's Fan",
    svgPath: '/quilt_blocks/45_grandmothers_fan.svg',
    commonSizes: ['12"+'],
    description: 'Fan-shaped curved petals',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'hen-and-chicks',
    name: 'hen_and_chicks',
    displayName: 'Hen and Chicks',
    svgPath: '/quilt_blocks/46_hen_and_chicks.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Mother hen with chicks',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'hourglass',
    name: 'hourglass',
    displayName: 'Hourglass',
    svgPath: '/quilt_blocks/47_hourglass.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Stacked triangle sand timer',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'jacobs-ladder',
    name: 'jacobs_ladder',
    displayName: "Jacob's Ladder",
    svgPath: '/quilt_blocks/48_jacobs_ladder.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Ladder rails with squares',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'lady-of-the-lake',
    name: 'lady_of_the_lake',
    displayName: 'Lady of the Lake',
    svgPath: '/quilt_blocks/49_lady_of_the_lake.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Curved wave triangles',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'maple-leaf',
    name: 'maple_leaf',
    displayName: 'Maple Leaf',
    svgPath: '/quilt_blocks/50_maple_leaf.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Leaf veins with HSTs',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'mariners-compass',
    name: 'mariners_compass',
    displayName: "Mariner's Compass",
    svgPath: '/quilt_blocks/51_mariners_compass.svg',
    commonSizes: ['12"+'],
    description: 'Nautical star with points',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'monkey-wrench',
    name: 'monkey_wrench',
    displayName: 'Monkey Wrench',
    svgPath: '/quilt_blocks/52_monkey_wrench.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Tool-shaped geometric',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'ocean-waves',
    name: 'ocean_waves',
    displayName: 'Ocean Waves',
    svgPath: '/quilt_blocks/53_ocean_waves.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Curved wave strips',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'pineapple',
    name: 'pineapple',
    displayName: 'Pineapple',
    svgPath: '/quilt_blocks/54_pineapple.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Log Cabin with diagonal strips',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'road-to-california',
    name: 'road_to_california',
    displayName: 'Road to California',
    svgPath: '/quilt_blocks/55_road_to_california.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Winding path triangles',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'snails-trail',
    name: 'snails_trail',
    displayName: "Snail's Trail",
    svgPath: '/quilt_blocks/56_snails_trail.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Spiraling log strips',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'storm-at-sea',
    name: 'storm_at_sea',
    displayName: 'Storm at Sea',
    svgPath: '/quilt_blocks/57_storm_at_sea.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Wavy diamond illusion',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'sunbonnet-sue',
    name: 'sunbonnet_sue',
    displayName: 'Sunbonnet Sue',
    svgPath: '/quilt_blocks/58_sunbonnet_sue.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Appliqué girl silhouette',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'variable-star',
    name: 'variable_star',
    displayName: 'Variable Star',
    svgPath: '/quilt_blocks/59_variable_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Star with changeable points',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'weathervane',
    name: 'weathervane',
    displayName: 'Weathervane',
    svgPath: '/quilt_blocks/60_weathervane.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Arrow and star combo',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'windmill',
    name: 'windmill',
    displayName: 'Windmill',
    svgPath: '/quilt_blocks/61_windmill.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Rotating blades',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: '54-40-or-fight',
    name: '54_40_or_fight',
    displayName: '54-40 or Fight',
    svgPath: '/quilt_blocks/62_54_40_or_fight.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Political star motif',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'aunt-sukeys-choice',
    name: 'aunt_sukeys_choice',
    displayName: "Aunt Sukey's Choice",
    svgPath: '/quilt_blocks/63_aunt_sukeys_choice.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Framed star variation',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'autumn-tints',
    name: 'autumn_tints',
    displayName: 'Autumn Tints',
    svgPath: '/quilt_blocks/64_autumn_tints.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Fall leaf color blocks',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'bachelors-puzzle',
    name: 'bachelors_puzzle',
    displayName: "Bachelor's Puzzle",
    svgPath: '/quilt_blocks/65_bachelors_puzzle.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Puzzle piece triangles',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'big-o',
    name: 'big_o',
    displayName: "Big 'O'",
    svgPath: '/quilt_blocks/66_big_o.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Circular ring effect',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'blazing-arrows',
    name: 'blazing_arrows',
    displayName: 'Blazing Arrows',
    svgPath: '/quilt_blocks/67_blazing_arrows.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Arrowhead points',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'bright-hopes',
    name: 'bright_hopes',
    displayName: 'Bright Hopes',
    svgPath: '/quilt_blocks/68_bright_hopes.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Hopeful star rays',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'buckeye-beauty',
    name: 'buckeye_beauty',
    displayName: 'Buckeye Beauty',
    svgPath: '/quilt_blocks/69_buckeye_beauty.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Ohio state flower star',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'cats-cradle',
    name: 'cats_cradle',
    displayName: "Cat's Cradle",
    svgPath: '/quilt_blocks/70_cats_cradle.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'String game illusion',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'chained-star',
    name: 'chained_star',
    displayName: 'Chained Star',
    svgPath: '/quilt_blocks/71_chained_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Linked star chain',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'cross-and-square',
    name: 'cross_and_square',
    displayName: 'Cross and Square',
    svgPath: '/quilt_blocks/72_cross_and_square.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Cross inside square frame',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'crowning-glory',
    name: 'crowning_glory',
    displayName: 'Crowning Glory',
    svgPath: '/quilt_blocks/73_crowning_glory.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Crown with jewel points',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'diamond-cross',
    name: 'diamond_cross',
    displayName: 'Diamond Cross',
    svgPath: '/quilt_blocks/74_diamond_cross.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Diamond-framed cross',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'dolly-madisons-star',
    name: 'dolly_madisons_star',
    displayName: "Dolly Madison's Star",
    svgPath: '/quilt_blocks/75_dolly_madisons_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Historical star design',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'double-t',
    name: 'double_t',
    displayName: 'Double T',
    svgPath: '/quilt_blocks/76_double_t.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Interlocking T shapes',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'duck-and-ducklings',
    name: 'duck_and_ducklings',
    displayName: 'Duck and Ducklings',
    svgPath: '/quilt_blocks/77_duck_and_ducklings.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Mother duck family',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'liberty-star',
    name: 'liberty_star',
    displayName: 'Liberty Star',
    svgPath: '/quilt_blocks/78_liberty_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Patriotic star',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'rocky-road-to-california',
    name: 'rocky_road_to_california',
    displayName: 'Rocky Road to California',
    svgPath: '/quilt_blocks/79_rocky_road_to_california.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Winding road path',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'split-nine-patch',
    name: 'split_nine_patch',
    displayName: 'Split Nine Patch',
    svgPath: '/quilt_blocks/80_split_nine_patch.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Nine-patch with diagonal split',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'star-and-cross',
    name: 'star_and_cross',
    displayName: 'Star and Cross',
    svgPath: '/quilt_blocks/81_star_and_cross.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Star overlapping cross',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'teddys-choice',
    name: 'teddys_choice',
    displayName: "Teddy's Choice",
    svgPath: '/quilt_blocks/82_teddys_choice.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Teddy bear motif',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'wheel-of-fortune',
    name: 'wheel_of_fortune',
    displayName: 'Wheel of Fortune',
    svgPath: '/quilt_blocks/83_wheel_of_fortune.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Spinning wheel',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'yankee-puzzle',
    name: 'yankee_puzzle',
    displayName: 'Yankee Puzzle',
    svgPath: '/quilt_blocks/84_yankee_puzzle.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'New England geometric',
    difficulty: 'intermediate',
    gridUnits: 2,
  },
  {
    id: 'air-castle',
    name: 'air_castle',
    displayName: 'Air Castle',
    svgPath: '/quilt_blocks/85_air_castle.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Floating castle towers',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'birds-eye-view',
    name: 'birds_eye_view',
    displayName: "Bird's Eye View",
    svgPath: '/quilt_blocks/86_birds_eye_view.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: "Bird's-eye geometric",
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'colonial-basket',
    name: 'colonial_basket',
    displayName: 'Colonial Basket',
    svgPath: '/quilt_blocks/87_colonial_basket.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Woven colonial basket',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'dove-in-the-window',
    name: 'dove_in_the_window',
    displayName: 'Dove in the Window',
    svgPath: '/quilt_blocks/88_dove_in_the_window.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Dove with window frame',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'grape-basket',
    name: 'grape_basket',
    displayName: 'Grape Basket',
    svgPath: '/quilt_blocks/89_grape_basket.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Fruit basket with grapes',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'hens-and-chickens',
    name: 'hens_and_chickens',
    displayName: 'Hens and Chickens',
    svgPath: '/quilt_blocks/90_hens_and_chickens.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Farmyard family',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'linoleum',
    name: 'linoleum',
    displayName: 'Linoleum',
    svgPath: '/quilt_blocks/91_linoleum.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Floor tile pattern',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'picture-frame',
    name: 'picture_frame',
    displayName: 'Picture Frame',
    svgPath: '/quilt_blocks/92_picture_frame.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Framed center square',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'red-cross',
    name: 'red_cross',
    displayName: 'Red Cross',
    svgPath: '/quilt_blocks/93_red_cross.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Red cross symbol',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'round-robin',
    name: 'round_robin',
    displayName: 'Round Robin',
    svgPath: '/quilt_blocks/94_round_robin.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Circular round design',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'trailing-star',
    name: 'trailing_star',
    displayName: 'Trailing Star',
    svgPath: '/quilt_blocks/95_trailing_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Comet-like trailing star',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 't-square',
    name: 't_square',
    displayName: 'T Square',
    svgPath: '/quilt_blocks/96_t_square.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: "Carpenter's T tool",
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'wandering-jew',
    name: 'wandering_jew',
    displayName: 'Wandering Jew',
    svgPath: '/quilt_blocks/97_wandering_jew.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Wandering path design',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'wedge-and-circle',
    name: 'wedge_and_circle',
    displayName: 'Wedge and Circle',
    svgPath: '/quilt_blocks/98_wedge_and_circle.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Curved wedge segments',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'western-spy',
    name: 'western_spy',
    displayName: 'Western Spy',
    svgPath: '/quilt_blocks/99_western_spy.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Spyglass telescope',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'snowflake',
    name: 'snowflake',
    displayName: 'Snowflake',
    svgPath: '/quilt_blocks/100_snowflake.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Six-pointed snowflake star',
    difficulty: 'advanced',
    gridUnits: 6,
  },
];

export const LAYOUT_OVERLAYS: LayoutOverlay[] = [
  {
    id: 'baby-quilt',
    name: 'baby_quilt',
    displayName: 'Baby Quilt',
    svgPath: '/quilt_layouts/01_baby_quilt.svg',
    dimensions: { width: 36, height: 46 },
    description: 'Perfect for newborns and infants',
    blockLayout: { cols: 4, rows: 5 },
  },
  {
    id: 'crib-quilt',
    name: 'crib_quilt',
    displayName: 'Crib Quilt',
    svgPath: '/quilt_layouts/02_crib_quilt.svg',
    dimensions: { width: 36, height: 52 },
    description: 'Standard crib size',
    blockLayout: { cols: 4, rows: 6 },
  },
  {
    id: 'throw-quilt',
    name: 'throw_quilt',
    displayName: 'Throw / Lap Quilt',
    svgPath: '/quilt_layouts/03_throw_quilt.svg',
    dimensions: { width: 50, height: 65 },
    description: 'Ideal for couch or lap use',
    blockLayout: { cols: 6, rows: 8 },
  },
  {
    id: 'twin-quilt',
    name: 'twin_quilt',
    displayName: 'Twin Quilt',
    svgPath: '/quilt_layouts/04_twin_quilt.svg',
    dimensions: { width: 66, height: 90 },
    description: 'Standard twin bed size',
    blockLayout: { cols: 8, rows: 12 },
  },
  {
    id: 'full-quilt',
    name: 'full_quilt',
    displayName: 'Full / Double Quilt',
    svgPath: '/quilt_layouts/05_full_quilt.svg',
    dimensions: { width: 80, height: 90 },
    description: 'Full/double bed size',
    blockLayout: { cols: 10, rows: 12 },
  },
  {
    id: 'queen-quilt',
    name: 'queen_quilt',
    displayName: 'Queen Quilt',
    svgPath: '/quilt_layouts/06_queen_quilt.svg',
    dimensions: { width: 88, height: 96 },
    description: 'Queen bed size',
    blockLayout: { cols: 11, rows: 13 },
  },
  {
    id: 'king-quilt',
    name: 'king_quilt',
    displayName: 'King Quilt',
    svgPath: '/quilt_layouts/07_king_quilt.svg',
    dimensions: { width: 104, height: 108 },
    description: 'King bed size',
    blockLayout: { cols: 13, rows: 15 },
  },
  {
    id: 'double-wedding-ring',
    name: 'double_wedding_ring',
    displayName: 'Double Wedding Ring',
    svgPath: '/quilt_layouts/08_double_wedding_ring.svg',
    dimensions: { width: 72, height: 88 },
    description: 'Interlocking rings — classic heirloom/wedding quilt',
  },
  {
    id: 'trip-around-world',
    name: 'trip_around_world',
    displayName: 'Trip Around the World',
    svgPath: '/quilt_layouts/09_trip_around_world.svg',
    dimensions: { width: 60, height: 80 },
    description: 'Concentric square rings radiating from center',
  },
  {
    id: 'yellow-brick-road',
    name: 'yellow_brick_road',
    displayName: 'Yellow Brick Road',
    svgPath: '/quilt_layouts/10_yellow_brick_road.svg',
    dimensions: { width: 54, height: 72 },
    description: 'Offset brick rectangles — beginner-friendly and quick to assemble',
  },
];

/**
 * Get a block overlay by ID
 */
export function getBlockOverlay(id: string): BlockOverlay | undefined {
  return BLOCK_OVERLAYS.find((b) => b.id === id);
}

/**
 * Get a layout overlay by ID
 */
export function getLayoutOverlay(id: string): LayoutOverlay | undefined {
  return LAYOUT_OVERLAYS.find((p) => p.id === id);
}

/**
 * Get all blocks by difficulty level
 */
export function getBlocksByDifficulty(difficulty: BlockOverlay['difficulty']): BlockOverlay[] {
  return BLOCK_OVERLAYS.filter((b) => b.difficulty === difficulty);
}

/**
 * Calculate how many blocks are needed for a given layout and block size
 */
export function calculateBlockCount(
  layout: LayoutOverlay,
  blockSize: number
): { cols: number; rows: number; total: number } {
  const cols = Math.ceil(layout.dimensions.width / blockSize);
  const rows = Math.ceil(layout.dimensions.height / blockSize);
  return { cols, rows, total: cols * rows };
}
