/**
 * Quilt Block Overlay Registry
 *
 * Maps block names to their SVG overlay files in /quilt_blocks/.
 * All block SVGs use a 300x300 viewBox with filled patches.
 */

export interface BlockOverlay {
  id: string;
  name: string;
  displayName: string;
  svgPath: string;
  commonSizes: string[];
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  gridUnits: number;
}

export const BLOCK_OVERLAYS: BlockOverlay[] = [
  {
    id: 'nine-patch',
    name: 'nine_patch',
    displayName: 'Nine Patch',
    svgPath: '/quilt_blocks/01_nine_patch.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9 squares in a 3×3 grid — the most fundamental quilt block',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'churn-dash',
    name: 'churn_dash',
    displayName: 'Churn Dash',
    svgPath: '/quilt_blocks/02_churn_dash.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '4 HSTs and 4 rectangles around a center square, resembling a butter churn',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'log-cabin',
    name: 'log_cabin',
    displayName: 'Log Cabin',
    svgPath: '/quilt_blocks/03_log_cabin.svg',
    commonSizes: ['6"', '8"', '12"'],
    description: 'Concentric strips around a central square, mimicking log cabin construction',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'ohio-star',
    name: 'ohio_star',
    displayName: 'Ohio Star',
    svgPath: '/quilt_blocks/04_ohio_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Classic 8-pointed star in a 9-patch layout using quarter-square triangles',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'bear-paw',
    name: 'bear_paw',
    displayName: 'Bear Paw',
    svgPath: '/quilt_blocks/05_bear_paw.svg',
    commonSizes: ['12"'],
    description: 'Squares and HSTs forming a bear paw shape with distinct claws',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'pinwheel',
    name: 'pinwheel',
    displayName: 'Pinwheel',
    svgPath: '/quilt_blocks/06_pinwheel.svg',
    commonSizes: ['3"', '4"', '5"', '6"', '8"'],
    description: '4 HSTs rotating around a center point creating a spinning effect',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'flying-geese',
    name: 'flying_geese',
    displayName: 'Flying Geese',
    svgPath: '/quilt_blocks/07_flying_geese.svg',
    commonSizes: ['2"x4"', '3"x6"'],
    description:
      'Rectangular block with a center triangle and two side triangles (width = 2× height)',
    difficulty: 'beginner',
    gridUnits: 6,
  },
  {
    id: 'drunkards-path',
    name: 'drunkards_path',
    displayName: "Drunkard's Path",
    svgPath: '/quilt_blocks/08_drunkards_path.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Quarter circle set in a square — great introduction to curved piecing',
    difficulty: 'advanced',
    gridUnits: 2,
  },
  {
    id: 'shoo-fly',
    name: 'shoo_fly',
    displayName: 'Shoo Fly',
    svgPath: '/quilt_blocks/09_shoo_fly.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with 4 HSTs and 4 squares around a center square',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'sawtooth-star',
    name: 'sawtooth_star',
    displayName: 'Sawtooth Star',
    svgPath: '/quilt_blocks/10_sawtooth_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '8-pointed star constructed from flying geese around a center square',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'friendship-star',
    name: 'friendship_star',
    displayName: 'Friendship Star',
    svgPath: '/quilt_blocks/11_friendship_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with HSTs arranged to form a four-pointed star',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'square-in-square',
    name: 'square_in_square',
    displayName: 'Square in a Square',
    svgPath: '/quilt_blocks/12_square_in_square.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Central square surrounded by 4 triangles creating a diamond illusion',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'rail-fence',
    name: 'rail_fence',
    displayName: 'Rail Fence',
    svgPath: '/quilt_blocks/13_rail_fence.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Simple striped square block — versatile for many layouts',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'card-trick',
    name: 'card_trick',
    displayName: 'Card Trick',
    svgPath: '/quilt_blocks/14_card_trick.svg',
    commonSizes: ['4.5"', '6"', '9"', '12"'],
    description: 'HST arrangement resembling playing cards in a 9-patch',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'double-star',
    name: 'double_star',
    displayName: 'Double Star',
    svgPath: '/quilt_blocks/15_double_star.svg',
    commonSizes: ['7.5"', '10"', '12.5"', '15"'],
    description: 'Layered star design with inner and outer star points',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'lone-star',
    name: 'lone_star',
    displayName: 'Lone Star',
    svgPath: '/quilt_blocks/16_lone_star.svg',
    commonSizes: ['12"+'],
    description:
      '8-pointed diamond star radiating from center — often used as a single-block quilt',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'tumbling-blocks',
    name: 'tumbling_blocks',
    displayName: 'Tumbling Blocks',
    svgPath: '/quilt_blocks/17_tumbling_blocks.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '3D cube illusion created with diamonds and careful color placement',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'dresden-plate',
    name: 'dresden_plate',
    displayName: 'Dresden Plate',
    svgPath: '/quilt_blocks/18_dresden_plate.svg',
    commonSizes: ['12"+'],
    description: 'Circular petal design with radiating wedges around a center circle',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'irish-chain',
    name: 'irish_chain',
    displayName: 'Irish Chain',
    svgPath: '/quilt_blocks/19_irish_chain.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch blocks and solid squares forming diagonal chain patterns',
    difficulty: 'beginner',
    gridUnits: 5,
  },
  {
    id: 'hst',
    name: 'hst',
    displayName: 'Half-Square Triangle',
    svgPath: '/quilt_blocks/20_hst.svg',
    commonSizes: ['2"', '3"', '4"', '6"', '8"', '12"'],
    description: 'Two triangles forming a square — the most versatile building block in quilting',
    difficulty: 'beginner',
    gridUnits: 1,
  },
  {
    id: 'four-patch',
    name: 'four_patch',
    displayName: 'Four Patch',
    svgPath: '/quilt_blocks/21_four_patch.svg',
    commonSizes: ['4"', '6"', '8"', '12"'],
    description: '4 squares in a 2×2 grid — the simplest patchwork block',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'double-four-patch',
    name: 'double_four_patch',
    displayName: 'Double Four Patch',
    svgPath: '/quilt_blocks/22_double_four_patch.svg',
    commonSizes: ['6"', '8"', '12"'],
    description: '2×2 grid with two four-patch units and two solid squares',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'snowball',
    name: 'snowball',
    displayName: 'Snowball',
    svgPath: '/quilt_blocks/23_snowball.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Square with corner triangles creating a soft octagonal shape',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'bow-tie',
    name: 'bow_tie',
    displayName: 'Bow Tie',
    svgPath: '/quilt_blocks/24_bow_tie.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Two diagonal squares connected by a center knot — a classic charm block',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'windmill',
    name: 'windmill',
    displayName: 'Windmill',
    svgPath: '/quilt_blocks/25_windmill.svg',
    commonSizes: ['4"', '6"', '8"', '12"'],
    description: '4 HSTs spinning clockwise like windmill blades',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'hourglass',
    name: 'hourglass',
    displayName: 'Hourglass',
    svgPath: '/quilt_blocks/26_hourglass.svg',
    commonSizes: ['4"', '6"', '8"', '12"'],
    description: 'Quarter-square triangle unit forming an hourglass silhouette',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'broken-dishes',
    name: 'broken_dishes',
    displayName: 'Broken Dishes',
    svgPath: '/quilt_blocks/27_broken_dishes.svg',
    commonSizes: ['4"', '6"', '8"', '12"'],
    description: '4 HSTs with dark halves meeting at center — a bold graphic block',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'variable-star',
    name: 'variable_star',
    displayName: 'Variable Star',
    svgPath: '/quilt_blocks/28_variable_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch star with triangle points on each side — endlessly versatile',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'evening-star',
    name: 'evening_star',
    displayName: 'Evening Star',
    svgPath: '/quilt_blocks/29_evening_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Star variant with elongated points and contrasting center',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'north-star',
    name: 'north_star',
    displayName: 'North Star',
    svgPath: '/quilt_blocks/30_north_star.svg',
    commonSizes: ['8"', '12"', '16"'],
    description: '8-pointed star on a 4×4 grid with strong diagonal lines',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'maple-leaf',
    name: 'maple_leaf',
    displayName: 'Maple Leaf',
    svgPath: '/quilt_blocks/31_maple_leaf.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'HSTs and squares forming a leaf shape with a diagonal stem',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'basket',
    name: 'basket',
    displayName: 'Basket',
    svgPath: '/quilt_blocks/32_basket.svg',
    commonSizes: ['9"', '12"'],
    description: 'Triangular basket shape with a handle — a beloved traditional block',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'grandmothers-fan',
    name: 'grandmothers_fan',
    displayName: "Grandmother's Fan",
    svgPath: '/quilt_blocks/33_grandmothers_fan.svg',
    commonSizes: ['9"', '12"', '18"'],
    description: 'Quarter-circle fan with alternating wedges — perfect for scraps',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'economy-block',
    name: 'economy_block',
    displayName: 'Economy Block',
    svgPath: '/quilt_blocks/34_economy_block.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Square-in-a-square creating a diamond center with corner triangles',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'yankee-puzzle',
    name: 'yankee_puzzle',
    displayName: 'Yankee Puzzle',
    svgPath: '/quilt_blocks/35_yankee_puzzle.svg',
    commonSizes: ['4"', '6"', '8"', '12"'],
    description: '4 HSTs in a spinning arrangement — great secondary patterns when tiled',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'dutchmans-puzzle',
    name: 'dutchmans_puzzle',
    displayName: "Dutchman's Puzzle",
    svgPath: '/quilt_blocks/36_dutchmans_puzzle.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '4 flying-geese units arranged in a pinwheel — bold and graphic',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'weather-vane',
    name: 'weather_vane',
    displayName: 'Weather Vane',
    svgPath: '/quilt_blocks/37_weather_vane.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with directional HST corners creating a spinning vane effect',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'anvil',
    name: 'anvil',
    displayName: 'Anvil',
    svgPath: '/quilt_blocks/38_anvil.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with HSTs forming an anvil silhouette',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'puss-in-corner',
    name: 'puss_in_corner',
    displayName: 'Puss in the Corner',
    svgPath: '/quilt_blocks/39_puss_in_corner.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with dark corner squares and center — a classic charm quilt block',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'corn-and-beans',
    name: 'corn_and_beans',
    displayName: 'Corn and Beans',
    svgPath: '/quilt_blocks/40_corn_and_beans.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with HSTs and solids — creates wonderful secondary patterns',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'gentlemans-fancy',
    name: 'gentlemans_fancy',
    displayName: "Gentleman's Fancy",
    svgPath: '/quilt_blocks/41_gentlemans_fancy.svg',
    commonSizes: ['9"', '12"', '15"'],
    description: 'Elaborate 9-patch with center diamond, corner HSTs, and rectangular accents',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'jacobs-ladder',
    name: 'jacobs_ladder',
    displayName: "Jacob's Ladder",
    svgPath: '/quilt_blocks/42_jacobs_ladder.svg',
    commonSizes: ['9"', '12"'],
    description: 'Alternating four-patch and HST units creating diagonal chains when tiled',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'monkey-wrench',
    name: 'monkey_wrench',
    displayName: 'Monkey Wrench',
    svgPath: '/quilt_blocks/43_monkey_wrench.svg',
    commonSizes: ['9"', '12"'],
    description: '9-patch with a rotating frame of rectangles and corner HSTs',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'courthouse-steps',
    name: 'courthouse_steps',
    displayName: 'Courthouse Steps',
    svgPath: '/quilt_blocks/44_courthouse_steps.svg',
    commonSizes: ['6"', '8"', '12"'],
    description: 'Symmetric Log Cabin variant with strips added to opposite sides',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'attic-windows',
    name: 'attic_windows',
    displayName: 'Attic Windows',
    svgPath: '/quilt_blocks/45_attic_windows.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '3D illusion of looking through a window with perspective shadows',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'crosses-and-losses',
    name: 'crosses_and_losses',
    displayName: 'Crosses and Losses',
    svgPath: '/quilt_blocks/46_crosses_and_losses.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Cross shape with HST corners — traditional block with strong geometry',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'goose-tracks',
    name: 'goose_tracks',
    displayName: 'Goose Tracks',
    svgPath: '/quilt_blocks/47_goose_tracks.svg',
    commonSizes: ['12"', '16"'],
    description: 'Center diamond with flying-geese tracks radiating to corners',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'handy-andy',
    name: 'handy_andy',
    displayName: 'Handy Andy',
    svgPath: '/quilt_blocks/48_handy_andy.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with HST sides and small diamond accents in corners',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'old-maids-puzzle',
    name: 'old_maids_puzzle',
    displayName: "Old Maid's Puzzle",
    svgPath: '/quilt_blocks/49_old_maids_puzzle.svg',
    commonSizes: ['4"', '6"', '8"', '12"'],
    description: '4 HSTs creating an S or Z shape — simple but effective',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'road-to-oklahoma',
    name: 'road_to_oklahoma',
    displayName: 'Road to Oklahoma',
    svgPath: '/quilt_blocks/50_road_to_oklahoma.svg',
    commonSizes: ['9"', '12"'],
    description: "Jacob's Ladder variation with a different diagonal road pattern",
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'double-nine-patch',
    name: 'double_nine_patch',
    displayName: 'Double Nine Patch',
    svgPath: '/quilt_blocks/51_double_nine_patch.svg',
    commonSizes: ['9"', '12"', '18"'],
    description: '9-patch where five positions contain mini nine-patches — great scrap block',
    difficulty: 'beginner',
    gridUnits: 9,
  },
  {
    id: 'disappearing-nine-patch',
    name: 'disappearing_nine_patch',
    displayName: 'Disappearing Nine Patch',
    svgPath: '/quilt_blocks/52_disappearing_nine_patch.svg',
    commonSizes: ['9"', '12"'],
    description: 'Nine patch cut and re-sewn to create unexpected secondary patterns',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'split-nine-patch',
    name: 'split_nine_patch',
    displayName: 'Split Nine Patch',
    svgPath: '/quilt_blocks/53_split_nine_patch.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with some squares split diagonally into HSTs',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'five-patch',
    name: 'five_patch',
    displayName: 'Five Patch',
    svgPath: '/quilt_blocks/54_five_patch.svg',
    commonSizes: ['10"', '15"'],
    description: '5×5 grid with checkerboard arrangement — foundation for many traditional designs',
    difficulty: 'beginner',
    gridUnits: 5,
  },
  {
    id: 't-block',
    name: 't_block',
    displayName: 'T-Block',
    svgPath: '/quilt_blocks/55_t_block.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Simple T-shape in a 9-patch grid — bold and graphic',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'spider-web',
    name: 'spider_web',
    displayName: 'Spider Web',
    svgPath: '/quilt_blocks/56_spider_web.svg',
    commonSizes: ['9"', '12"'],
    description: '8 triangles radiating from center in an octagonal web pattern',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'kaleidoscope',
    name: 'kaleidoscope',
    displayName: 'Kaleidoscope',
    svgPath: '/quilt_blocks/57_kaleidoscope.svg',
    commonSizes: ['9"', '12"'],
    description: '8 alternating triangles meeting at center like looking through a kaleidoscope',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'mosaic',
    name: 'mosaic',
    displayName: 'Mosaic',
    svgPath: '/quilt_blocks/58_mosaic.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch of HSTs creating a tessellated mosaic effect',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'roman-stripe',
    name: 'roman_stripe',
    displayName: 'Roman Stripe',
    svgPath: '/quilt_blocks/59_roman_stripe.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Diagonal stripes in one triangle half — a staple of string quilting',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'chinese-coins',
    name: 'chinese_coins',
    displayName: 'Chinese Coins',
    svgPath: '/quilt_blocks/60_chinese_coins.svg',
    commonSizes: ['3"×6"', '4"×8"'],
    description: 'Horizontal strips of varying colors stacked in a column — perfect for scraps',
    difficulty: 'beginner',
    gridUnits: 1,
  },
  {
    id: 'snails-trail',
    name: 'snails_trail',
    displayName: "Snail's Trail",
    svgPath: '/quilt_blocks/61_snails_trail.svg',
    commonSizes: ['9"', '12"'],
    description: 'Spiraling triangles rotating outward from center — mesmerizing when tiled',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'storm-at-sea',
    name: 'storm_at_sea',
    displayName: 'Storm at Sea',
    svgPath: '/quilt_blocks/62_storm_at_sea.svg',
    commonSizes: ['12"', '16"'],
    description:
      'Square-in-square center with wave-like triangle surrounds — an optical illusion classic',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'carpenters-star',
    name: 'carpenters_star',
    displayName: "Carpenter's Star",
    svgPath: '/quilt_blocks/63_carpenters_star.svg',
    commonSizes: ['12"', '16"'],
    description: 'Large 8-pointed star combining square-in-square with radiating star points',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'lemoyne-star',
    name: 'lemoyne_star',
    displayName: 'LeMoyne Star',
    svgPath: '/quilt_blocks/64_lemoyne_star.svg',
    commonSizes: ['12"', '16"'],
    description:
      '8-pointed star of 8 diamond shapes — named for the LeMoyne brothers of New Orleans',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'morning-star',
    name: 'morning_star',
    displayName: 'Morning Star',
    svgPath: '/quilt_blocks/65_morning_star.svg',
    commonSizes: ['12"', '16"'],
    description: '8-pointed star with broken points and accent triangles between arms',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'hunters-star',
    name: 'hunters_star',
    displayName: "Hunter's Star",
    svgPath: '/quilt_blocks/66_hunters_star.svg',
    commonSizes: ['12"', '16"'],
    description: 'Two interlocking rotated squares creating an 8-pointed star illusion',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'prairie-star',
    name: 'prairie_star',
    displayName: 'Prairie Star',
    svgPath: '/quilt_blocks/67_prairie_star.svg',
    commonSizes: ['9"', '12"'],
    description: 'Large star on a 3×3 grid with prominent points in the side positions',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'rolling-star',
    name: 'rolling_star',
    displayName: 'Rolling Star',
    svgPath: '/quilt_blocks/68_rolling_star.svg',
    commonSizes: ['12"', '16"'],
    description: '8-pointed star with offset points creating a spinning motion effect',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'blazing-star',
    name: 'blazing_star',
    displayName: 'Blazing Star',
    svgPath: '/quilt_blocks/69_blazing_star.svg',
    commonSizes: ['12"', '16"'],
    description: 'Multi-layered star with inner and outer point rings — a show-stopper',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'mexican-star',
    name: 'mexican_star',
    displayName: 'Mexican Star',
    svgPath: '/quilt_blocks/70_mexican_star.svg',
    commonSizes: ['12"', '16"'],
    description: '8-pointed star with elongated thin diamond points',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'cathedral-star',
    name: 'cathedral_star',
    displayName: 'Cathedral Star',
    svgPath: '/quilt_blocks/71_cathedral_star.svg',
    commonSizes: ['12"', '16"'],
    description: 'Gothic-inspired star with arched elements suggesting cathedral windows',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'broken-star',
    name: 'broken_star',
    displayName: 'Broken Star',
    svgPath: '/quilt_blocks/72_broken_star.svg',
    commonSizes: ['12"+'],
    description: 'Expanded LeMoyne star with diamond points broken into smaller segments',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'star-of-bethlehem',
    name: 'star_of_bethlehem',
    displayName: 'Star of Bethlehem',
    svgPath: '/quilt_blocks/73_star_of_bethlehem.svg',
    commonSizes: ['12"+'],
    description: 'Large radiating 8-pointed star with concentric diamond rings',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'mariners-compass',
    name: 'mariners_compass',
    displayName: "Mariner's Compass",
    svgPath: '/quilt_blocks/74_mariners_compass.svg',
    commonSizes: ['12"', '16"', '24"'],
    description: '16-point compass rose with alternating large and small points',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'ocean-waves',
    name: 'ocean_waves',
    displayName: 'Ocean Waves',
    svgPath: '/quilt_blocks/75_ocean_waves.svg',
    commonSizes: ['9"', '12"'],
    description: 'HSTs arranged in diagonal rows creating a rolling wave pattern',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'steps-to-altar',
    name: 'steps_to_altar',
    displayName: 'Steps to the Altar',
    svgPath: '/quilt_blocks/76_steps_to_altar.svg',
    commonSizes: ['10"', '15"'],
    description: 'Stepped diagonal rectangles ascending like stairs — a wedding quilt favorite',
    difficulty: 'intermediate',
    gridUnits: 5,
  },
  {
    id: 'spinning-top',
    name: 'spinning_top',
    displayName: 'Spinning Top',
    svgPath: '/quilt_blocks/77_spinning_top.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Asymmetric triangles arranged in quadrants suggesting clockwise rotation',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'winged-square',
    name: 'winged_square',
    displayName: 'Winged Square',
    svgPath: '/quilt_blocks/78_winged_square.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Center square with wing triangles on all four sides',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'cross-and-crown',
    name: 'cross_and_crown',
    displayName: 'Cross and Crown',
    svgPath: '/quilt_blocks/79_cross_and_crown.svg',
    commonSizes: ['9"', '12"', '15"'],
    description: 'Cross shape with crown-like triangular points on each arm',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'devils-claw',
    name: 'devils_claw',
    displayName: "Devil's Claw",
    svgPath: '/quilt_blocks/80_devils_claw.svg',
    commonSizes: ['9"', '12"'],
    description: '4 angular claw shapes reaching from corners toward center',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'whirlwind',
    name: 'whirlwind',
    displayName: 'Whirlwind',
    svgPath: '/quilt_blocks/81_whirlwind.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Strong spinning triangles with secondary pieces creating a spiral whirlwind',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'double-pinwheel',
    name: 'double_pinwheel',
    displayName: 'Double Pinwheel',
    svgPath: '/quilt_blocks/82_double_pinwheel.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Two overlapping pinwheel patterns creating a layered spinning effect',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'chevron',
    name: 'chevron',
    displayName: 'Chevron',
    svgPath: '/quilt_blocks/83_chevron.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'V-shaped stripes stacking from bottom to top — bold and modern',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'schoolhouse',
    name: 'schoolhouse',
    displayName: 'Schoolhouse',
    svgPath: '/quilt_blocks/84_schoolhouse.svg',
    commonSizes: ['10"', '12"'],
    description: 'Pictorial block with triangular roof, door, and windows — a quilting classic',
    difficulty: 'intermediate',
    gridUnits: 5,
  },
  {
    id: 'pine-tree',
    name: 'pine_tree',
    displayName: 'Pine Tree',
    svgPath: '/quilt_blocks/85_pine_tree.svg',
    commonSizes: ['9"', '12"'],
    description:
      'Stacked triangle tiers forming a pine tree with a trunk — perfect for winter quilts',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'tree-of-life',
    name: 'tree_of_life',
    displayName: 'Tree of Life',
    svgPath: '/quilt_blocks/86_tree_of_life.svg',
    commonSizes: ['12"', '16"'],
    description: 'Stylized tree with central trunk and branching HST leaves',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'sunflower',
    name: 'sunflower',
    displayName: 'Sunflower',
    svgPath: '/quilt_blocks/87_sunflower.svg',
    commonSizes: ['12"', '16"'],
    description: 'Circular flower with radiating petal wedges and center circle',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'tulip-block',
    name: 'tulip_block',
    displayName: 'Tulip Block',
    svgPath: '/quilt_blocks/88_tulip_block.svg',
    commonSizes: ['9"', '12"'],
    description: 'Stylized tulip with 3-triangle head, stem, and leaves',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'carolina-lily',
    name: 'carolina_lily',
    displayName: 'Carolina Lily',
    svgPath: '/quilt_blocks/89_carolina_lily.svg',
    commonSizes: ['12"', '16"'],
    description: '3 diamond petals fanned on a stem — a Southern quilting tradition',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'cactus-basket',
    name: 'cactus_basket',
    displayName: 'Cactus Basket',
    svgPath: '/quilt_blocks/90_cactus_basket.svg',
    commonSizes: ['12"'],
    description: 'Triangular basket with angular cactus arms rising above',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'butterfly',
    name: 'butterfly',
    displayName: 'Butterfly',
    svgPath: '/quilt_blocks/91_butterfly.svg',
    commonSizes: ['9"', '12"'],
    description: 'Symmetrical butterfly with upper and lower wing sections and central body',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'lily',
    name: 'lily',
    displayName: 'Lily',
    svgPath: '/quilt_blocks/92_lily.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '3-petal lily on a 9-patch grid with HST petals, leaves, and stem',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'pineapple',
    name: 'pineapple',
    displayName: 'Pineapple',
    svgPath: '/quilt_blocks/93_pineapple.svg',
    commonSizes: ['12"', '16"'],
    description: 'Log Cabin variation with diagonal concentric rings — foundation piecing favorite',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'zigzag',
    name: 'zigzag',
    displayName: 'Zigzag',
    svgPath: '/quilt_blocks/94_zigzag.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Alternating triangles forming a bold zigzag stripe',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'herringbone',
    name: 'herringbone',
    displayName: 'Herringbone',
    svgPath: '/quilt_blocks/95_herringbone.svg',
    commonSizes: ['6"', '9"', '12"'],
    description:
      'Parallelogram strips in alternating directions creating a woven herringbone weave',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'bricks',
    name: 'bricks',
    displayName: 'Bricks',
    svgPath: '/quilt_blocks/96_bricks.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Offset rectangular bricks in stacked rows — easy and versatile',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'trip-around-world',
    name: 'trip_around_world',
    displayName: 'Trip Around the World',
    svgPath: '/quilt_blocks/97_trip_around_world.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Concentric diamond rings radiating from center — stunning in color gradients',
    difficulty: 'beginner',
    gridUnits: 5,
  },
  {
    id: 'cathedral-windows',
    name: 'cathedral_windows',
    displayName: 'Cathedral Windows',
    svgPath: '/quilt_blocks/98_cathedral_windows.svg',
    commonSizes: ['12"', '16"'],
    description: 'Overlapping curved shapes suggesting Gothic stained glass windows',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'double-wedding-ring',
    name: 'double_wedding_ring',
    displayName: 'Double Wedding Ring',
    svgPath: '/quilt_blocks/99_double_wedding_ring.svg',
    commonSizes: ['12"', '16"'],
    description: 'Two interlocking circular arcs — the ultimate wedding quilt block',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'grandmothers-flower-garden',
    name: 'grandmothers_flower_garden',
    displayName: "Grandmother's Flower Garden",
    svgPath: '/quilt_blocks/100_grandmothers_flower_garden.svg',
    commonSizes: ['9"', '12"'],
    description:
      'Center hexagon with ring of 6 hexagons forming a flower — English paper piecing classic',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'crown-royal',
    name: 'crown_royal',
    displayName: 'Crown Royal',
    svgPath: '/quilt_blocks/101_crown_royal.svg',
    commonSizes: ['9"', '12"'],
    description: '3-point crown with gems and band — regal and bold',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'rose-of-sharon',
    name: 'rose_of_sharon',
    displayName: 'Rose of Sharon',
    svgPath: '/quilt_blocks/102_rose_of_sharon.svg',
    commonSizes: ['12"', '16"', '18"'],
    description: '4 curved petals with leaves and center circle — a beloved appliqué block',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'bargello-strip',
    name: 'bargello_strip',
    displayName: 'Bargello Strip',
    svgPath: '/quilt_blocks/103_bargello_strip.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Vertical columns with wave-like color progression — inspired by needlepoint',
    difficulty: 'beginner',
    gridUnits: 6,
  },
  {
    id: 'dove-at-window',
    name: 'dove_at_window',
    displayName: 'Dove at the Window',
    svgPath: '/quilt_blocks/104_dove_at_window.svg',
    commonSizes: ['12"', '16"'],
    description: 'Center diamond with triangular window frames and HST border',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'grandmothers-choice',
    name: 'grandmothers_choice',
    displayName: "Grandmother's Choice",
    svgPath: '/quilt_blocks/105_grandmothers_choice.svg',
    commonSizes: ['9"', '12"', '15"'],
    description: '9-patch with center diamond, corner HSTs, and rectangular side pieces',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
];

/**
 * Get a block overlay by ID
 */
export function getBlockOverlay(id: string): BlockOverlay | undefined {
  return BLOCK_OVERLAYS.find((b) => b.id === id);
}

/**
 * Get all blocks by difficulty level
 */
export function getBlocksByDifficulty(difficulty: BlockOverlay['difficulty']): BlockOverlay[] {
  return BLOCK_OVERLAYS.filter((b) => b.difficulty === difficulty);
}
