/**
 * Quilt Block & Layout Overlay Registry
 *
 * Maps block and layout names to their SVG overlay files in /quilt_blocks/ and /quilt_layouts/.
 * All block SVGs use a 300×300 viewBox with filled patches.
 * Layout SVGs use proportional viewBoxes at 10px/inch with structural data-role attributes.
 * Layouts are fixed-aspect-ratio worktables: resizable but always maintain proportions.
 */

export interface BlockOverlay {
  id: string;
  name: string;
  displayName: string;
  svgPath: string;
  commonSizes: string[];
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  gridUnits: number;
}

export interface LayoutOverlay {
  id: string;
  name: string;
  displayName: string;
  svgPath: string;
  dimensions: { width: number; height: number };
  description: string;
  blockLayout?: { cols: number; rows: number };
}

export const BLOCK_OVERLAYS: BlockOverlay[] = [
  {
    id: 'nine-patch',
    name: 'nine_patch',
    displayName: 'Nine Patch',
    svgPath: '/quilt_blocks/01_nine_patch.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9 squares in a 3×3 grid — the most fundamental quilt block',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'churn-dash',
    name: 'churn_dash',
    displayName: 'Churn Dash',
    svgPath: '/quilt_blocks/02_churn_dash.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '4 HSTs and 4 rectangles around a center square',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'log-cabin',
    name: 'log_cabin',
    displayName: 'Log Cabin',
    svgPath: '/quilt_blocks/03_log_cabin.svg',
    commonSizes: ['6"', '8"', '12"'],
    description: 'Concentric strips around a central square',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'ohio-star',
    name: 'ohio_star',
    displayName: 'Ohio Star',
    svgPath: '/quilt_blocks/04_ohio_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Classic 8-pointed star using quarter-square triangles',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'bear-paw',
    name: 'bear_paw',
    displayName: 'Bear Paw',
    svgPath: '/quilt_blocks/05_bear_paw.svg',
    commonSizes: ['12"'],
    description: 'Squares and HSTs forming a bear paw shape with claws',
    difficulty: 'intermediate',
    gridUnits: 7,
  },
  {
    id: 'sawtooth-star',
    name: 'sawtooth_star',
    displayName: 'Sawtooth Star',
    svgPath: '/quilt_blocks/06_sawtooth_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '8-pointed star from flying geese around a center square',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'flying-geese',
    name: 'flying_geese',
    displayName: 'Flying Geese',
    svgPath: '/quilt_blocks/07_flying_geese.svg',
    commonSizes: ['2"×4"', '3"×6"'],
    description: 'Center triangle with two side triangles (width = 2× height)',
    difficulty: 'beginner',
    gridUnits: 6,
  },
  {
    id: 'drunkards-path',
    name: 'drunkards_path',
    displayName: "Drunkard's Path",
    svgPath: '/quilt_blocks/08_drunkards_path.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Quarter circle set in a square — intro to curved piecing',
    difficulty: 'advanced',
    gridUnits: 2,
  },
  {
    id: 'hst',
    name: 'hst',
    displayName: 'Half-Square Triangle',
    svgPath: '/quilt_blocks/09_hst.svg',
    commonSizes: ['2"', '3"', '4"', '6"', '8"', '12"'],
    description: 'Two triangles forming a square — the most versatile building block',
    difficulty: 'beginner',
    gridUnits: 1,
  },
  {
    id: 'four-patch',
    name: 'four_patch',
    displayName: 'Four Patch',
    svgPath: '/quilt_blocks/10_four_patch.svg',
    commonSizes: ['3"', '6"', '9"'],
    description: 'Basic 2×2 grid of alternating squares',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'friendship-star',
    name: 'friendship_star',
    displayName: 'Friendship Star',
    svgPath: '/quilt_blocks/11_friendship_star.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with HSTs arranged to form a four-pointed star',
    difficulty: 'beginner',
    gridUnits: 3,
  },
  {
    id: 'bow-tie',
    name: 'bow_tie',
    displayName: 'Bow Tie',
    svgPath: '/quilt_blocks/12_bow_tie.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Bow shape with squares and corner triangles',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'hourglass',
    name: 'hourglass',
    displayName: 'Hourglass',
    svgPath: '/quilt_blocks/13_hourglass.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Quarter-square triangles forming an hourglass shape',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'broken-dishes',
    name: 'broken_dishes',
    displayName: 'Broken Dishes',
    svgPath: '/quilt_blocks/14_broken_dishes.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '4 HSTs arranged in a pinwheel variation',
    difficulty: 'beginner',
    gridUnits: 2,
  },
  {
    id: 'double-star',
    name: 'double_star',
    displayName: 'Double Star',
    svgPath: '/quilt_blocks/15_double_star.svg',
    commonSizes: ['10"', '12"', '15"'],
    description: 'Layered star design with inner and outer star points',
    difficulty: 'advanced',
    gridUnits: 6,
  },
  {
    id: 'economy-block',
    name: 'economy_block',
    displayName: 'Economy Block',
    svgPath: '/quilt_blocks/16_economy_block.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Square-in-square creating a diamond illusion',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'dutchmans-puzzle',
    name: 'dutchmans_puzzle',
    displayName: "Dutchman's Puzzle",
    svgPath: '/quilt_blocks/17_dutchmans_puzzle.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Flying geese arranged in a rotating puzzle layout',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'dresden-plate',
    name: 'dresden_plate',
    displayName: 'Dresden Plate',
    svgPath: '/quilt_blocks/18_dresden_plate.svg',
    commonSizes: ['12"+'],
    description: 'Circular petal design with radiating wedges',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'anvil',
    name: 'anvil',
    displayName: 'Anvil',
    svgPath: '/quilt_blocks/19_anvil.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Anvil-shaped triangles and squares in a 9-patch',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'puss-in-corner',
    name: 'puss_in_corner',
    displayName: 'Puss in the Corner',
    svgPath: '/quilt_blocks/20_puss_in_corner.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '9-patch with four-patch corners and center square',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'corn-and-beans',
    name: 'corn_and_beans',
    displayName: 'Corn and Beans',
    svgPath: '/quilt_blocks/21_corn_and_beans.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Farm motif with HSTs and squares',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'gentlemans-fancy',
    name: 'gentlemans_fancy',
    displayName: "Gentleman's Fancy",
    svgPath: '/quilt_blocks/22_gentlemans_fancy.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Star variation with layered triangles',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'jacobs-ladder',
    name: 'jacobs_ladder',
    displayName: "Jacob's Ladder",
    svgPath: '/quilt_blocks/23_jacobs_ladder.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Four-patches and HSTs forming a diagonal path',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'courthouse-steps',
    name: 'courthouse_steps',
    displayName: 'Courthouse Steps',
    svgPath: '/quilt_blocks/24_courthouse_steps.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Log Cabin variation with symmetric concentric strips',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'attic-windows',
    name: 'attic_windows',
    displayName: 'Attic Windows',
    svgPath: '/quilt_blocks/25_attic_windows.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: '3D window frame illusion with parallelogram sides',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'handy-andy',
    name: 'handy_andy',
    displayName: 'Handy Andy',
    svgPath: '/quilt_blocks/26_handy_andy.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Star with extended arms and corner HSTs',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'old-maids-puzzle',
    name: 'old_maids_puzzle',
    displayName: "Old Maid's Puzzle",
    svgPath: '/quilt_blocks/27_old_maids_puzzle.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'HSTs arranged in a rotating puzzle pattern',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'road-to-oklahoma',
    name: 'road_to_oklahoma',
    displayName: 'Road to Oklahoma',
    svgPath: '/quilt_blocks/28_road_to_oklahoma.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Winding path of triangles and squares',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'double-nine-patch',
    name: 'double_nine_patch',
    displayName: 'Double Nine Patch',
    svgPath: '/quilt_blocks/29_double_nine_patch.svg',
    commonSizes: ['9"', '12"', '15"'],
    description: 'Nine-patch within a nine-patch for nested grid effect',
    difficulty: 'beginner',
    gridUnits: 9,
  },
  {
    id: 'snails-trail',
    name: 'snails_trail',
    displayName: "Snail's Trail",
    svgPath: '/quilt_blocks/30_snails_trail.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Spiraling triangles creating a snail shell illusion',
    difficulty: 'advanced',
    gridUnits: 4,
  },
  {
    id: 'lemoyne-star',
    name: 'lemoyne_star',
    displayName: 'LeMoyne Star',
    svgPath: '/quilt_blocks/31_lemoyne_star.svg',
    commonSizes: ['12"+'],
    description: '8-pointed star from 8 identical diamonds',
    difficulty: 'advanced',
    gridUnits: 8,
  },
  {
    id: 'double-pinwheel',
    name: 'double_pinwheel',
    displayName: 'Double Pinwheel',
    svgPath: '/quilt_blocks/32_double_pinwheel.svg',
    commonSizes: ['6"', '8"', '12"'],
    description: 'Two layered rotating HST pinwheels',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'zigzag',
    name: 'zigzag',
    displayName: 'Zigzag',
    svgPath: '/quilt_blocks/33_zigzag.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'HSTs forming a zigzag stripe pattern',
    difficulty: 'beginner',
    gridUnits: 4,
  },
  {
    id: 'dove-at-window',
    name: 'dove_at_window',
    displayName: 'Dove at the Window',
    svgPath: '/quilt_blocks/34_dove_at_window.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Dove motif with window frame triangles',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'grandmothers-choice',
    name: 'grandmothers_choice',
    displayName: "Grandmother's Choice",
    svgPath: '/quilt_blocks/35_grandmothers_choice.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Traditional star variation with HST points',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'corner-star',
    name: 'corner_star',
    displayName: 'Corner Star',
    svgPath: '/quilt_blocks/36_corner_star.svg',
    commonSizes: ['12"'],
    description: 'Nine-patch center on point with flying geese star points',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'cyclone',
    name: 'cyclone',
    displayName: 'Cyclone',
    svgPath: '/quilt_blocks/37_cyclone.svg',
    commonSizes: ['9"', '12"'],
    description: 'Center square with 4 flying geese spiraling in a pinwheel',
    difficulty: 'intermediate',
    gridUnits: 3,
  },
  {
    id: 'greek-cross',
    name: 'greek_cross',
    displayName: 'Greek Cross',
    svgPath: '/quilt_blocks/38_greek_cross.svg',
    commonSizes: ['6"', '9"', '12"'],
    description: 'Cross shape with HST corner patches',
    difficulty: 'intermediate',
    gridUnits: 5,
  },
  {
    id: 'honey-bee',
    name: 'honey_bee',
    displayName: 'Honey Bee',
    svgPath: '/quilt_blocks/39_honey_bee.svg',
    commonSizes: ['12"'],
    description: 'Nine-patch center with lattice borders and corner squares',
    difficulty: 'intermediate',
    gridUnits: 5,
  },
  {
    id: 'homestead',
    name: 'homestead',
    displayName: 'Homestead',
    svgPath: '/quilt_blocks/40_homestead.svg',
    commonSizes: ['10"', '12"'],
    description: 'Star with layered inner and outer flying geese in multiple colors',
    difficulty: 'intermediate',
    gridUnits: 5,
  },
  {
    id: 'winged-arrow',
    name: 'winged_arrow',
    displayName: 'Winged Arrow',
    svgPath: '/quilt_blocks/41_winged_arrow.svg',
    commonSizes: ['8"', '12"'],
    description: '4 quarter-square triangle units creating arrow wing shapes',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'hands-all-around',
    name: 'hands_all_around',
    displayName: 'Hands All Around',
    svgPath: '/quilt_blocks/42_hands_all_around.svg',
    commonSizes: ['12"'],
    description: 'Center diamond with flying geese star points and HST sides',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'scrappy-star',
    name: 'scrappy_star',
    displayName: 'Scrappy Star',
    svgPath: '/quilt_blocks/43_scrappy_star.svg',
    commonSizes: ['12"'],
    description: 'Star with scrappy nine-patch center and flying geese points',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'leahs-star',
    name: 'leahs_star',
    displayName: "Leah's Star",
    svgPath: '/quilt_blocks/44_leahs_star.svg',
    commonSizes: ['8"', '12"'],
    description: 'Two-color star with flying geese points and HST corners',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'star-bright',
    name: 'star_bright',
    displayName: 'Star Bright',
    svgPath: '/quilt_blocks/45_star_bright.svg',
    commonSizes: ['12"'],
    description: 'Pinwheel star with flying geese and scrappy HST center',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'merry-go-round',
    name: 'merry_go_round',
    displayName: 'Merry Go Round',
    svgPath: '/quilt_blocks/46_merry_go_round.svg',
    commonSizes: ['12"'],
    description: 'Large HSTs creating a spinning windmill effect',
    difficulty: 'intermediate',
    gridUnits: 2,
  },
  {
    id: 'nine-patch-star',
    name: 'nine_patch_star',
    displayName: 'Nine-Patch Star',
    svgPath: '/quilt_blocks/47_nine_patch_star.svg',
    commonSizes: ['12"'],
    description: 'Nine-patch center surrounded by flying geese star points',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'indian-meadow',
    name: 'indian_meadow',
    displayName: 'Indian Meadow',
    svgPath: '/quilt_blocks/48_indian_meadow.svg',
    commonSizes: ['10"', '12"'],
    description: 'Flying geese cross pattern with two-color HST corners',
    difficulty: 'intermediate',
    gridUnits: 4,
  },
  {
    id: 'prickly-pear',
    name: 'prickly_pear',
    displayName: 'Prickly Pear',
    svgPath: '/quilt_blocks/49_prickly_pear.svg',
    commonSizes: ['12"'],
    description: 'Center diamond with sawtooth triangles around the border',
    difficulty: 'intermediate',
    gridUnits: 6,
  },
  {
    id: 'scrap-bag',
    name: 'scrap_bag',
    displayName: 'Scrap Bag',
    svgPath: '/quilt_blocks/50_scrap_bag.svg',
    commonSizes: ['12"'],
    description: 'Nested diamond star with HSTs and accent corner squares',
    difficulty: 'intermediate',
    gridUnits: 5,
  },
];

export const LAYOUT_OVERLAYS: LayoutOverlay[] = [
  {
    id: 'straight-3x3',
    name: 'straight_3x3',
    displayName: 'Straight Set 3×3',
    svgPath: '/quilt_layouts/straight_3x3.svg',
    dimensions: { width: 36, height: 36 },
    description: '3×3 grid of blocks edge-to-edge',
    blockLayout: { cols: 3, rows: 3 },
  },
  {
    id: 'straight-4x4',
    name: 'straight_4x4',
    displayName: 'Straight Set 4×4',
    svgPath: '/quilt_layouts/straight_4x4.svg',
    dimensions: { width: 48, height: 48 },
    description: '4×4 grid of blocks edge-to-edge',
    blockLayout: { cols: 4, rows: 4 },
  },
  {
    id: 'straight-5x5',
    name: 'straight_5x5',
    displayName: 'Straight Set 5×5',
    svgPath: '/quilt_layouts/straight_5x5.svg',
    dimensions: { width: 60, height: 60 },
    description: '5×5 grid of blocks edge-to-edge',
    blockLayout: { cols: 5, rows: 5 },
  },
  {
    id: 'sashing-3x3',
    name: 'sashing_3x3',
    displayName: 'Sashing 3×3',
    svgPath: '/quilt_layouts/sashing_3x3.svg',
    dimensions: { width: 40, height: 40 },
    description: '3×3 grid with sashing strips and cornerstones',
    blockLayout: { cols: 3, rows: 3 },
  },
  {
    id: 'sashing-4x4',
    name: 'sashing_4x4',
    displayName: 'Sashing 4×4',
    svgPath: '/quilt_layouts/sashing_4x4.svg',
    dimensions: { width: 54, height: 54 },
    description: '4×4 grid with sashing strips and cornerstones',
    blockLayout: { cols: 4, rows: 4 },
  },
  {
    id: 'on-point-3x3',
    name: 'on_point_3x3',
    displayName: 'On Point 3×3',
    svgPath: '/quilt_layouts/on_point_3x3.svg',
    dimensions: { width: 51, height: 51 },
    description: '3×3 blocks set on point with setting triangles',
    blockLayout: { cols: 3, rows: 3 },
  },
  {
    id: 'on-point-2x2-border',
    name: 'on_point_2x2_border',
    displayName: 'On Point 2×2 with Border',
    svgPath: '/quilt_layouts/on_point_2x2_border.svg',
    dimensions: { width: 36, height: 36 },
    description: '2×2 blocks on point with border — Garden Gate style',
    blockLayout: { cols: 2, rows: 2 },
  },
  {
    id: 'strippy-5col',
    name: 'strippy_5col',
    displayName: 'Strippy 5 Column',
    svgPath: '/quilt_layouts/strippy_5col.svg',
    dimensions: { width: 44, height: 60 },
    description: '3 block columns separated by vertical sashing strips',
    blockLayout: { cols: 3, rows: 5 },
  },
  {
    id: 'lattice-5x3',
    name: 'lattice_5x3',
    displayName: 'Lattice 5×3',
    svgPath: '/quilt_layouts/lattice_5x3.svg',
    dimensions: { width: 26, height: 34 },
    description: '5×3 wall hanging with horizontal lattice strips — Country Star style',
    blockLayout: { cols: 5, rows: 3 },
  },
  {
    id: 'medallion-center',
    name: 'medallion_center',
    displayName: 'Medallion Center',
    svgPath: '/quilt_layouts/medallion_center.svg',
    dimensions: { width: 44, height: 44 },
    description: 'Center medallion block with concentric borders',
  },
];

/**
 * Get a block overlay by ID
 */
export function getBlockOverlay(id: string): BlockOverlay | undefined {
  return BLOCK_OVERLAYS.find((b) => b.id === id);
}

/**
 * Get a layout overlay by ID
 */
export function getLayoutOverlay(id: string): LayoutOverlay | undefined {
  return LAYOUT_OVERLAYS.find((p) => p.id === id);
}

/**
 * Get all blocks by difficulty level
 */
export function getBlocksByDifficulty(difficulty: BlockOverlay['difficulty']): BlockOverlay[] {
  return BLOCK_OVERLAYS.filter((b) => b.difficulty === difficulty);
}

/**
 * Calculate how many blocks are needed for a given layout and block size
 */
export function calculateBlockCount(
  layout: LayoutOverlay,
  blockSize: number
): { cols: number; rows: number; total: number } {
  const cols = Math.ceil(layout.dimensions.width / blockSize);
  const rows = Math.ceil(layout.dimensions.height / blockSize);
  return { cols, rows, total: cols * rows };
}
