import { Post, User, Comment } from '@/types/social';

const users: User[] = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    username: 'sarahm',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    bio: 'Travel enthusiast & photographer',
    followers: 12400,
    following: 892,
  },
  {
    id: '2',
    name: 'Alex Chen',
    username: 'alexc',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    bio: 'Software engineer | Coffee lover',
    followers: 8920,
    following: 432,
  },
  {
    id: '3',
    name: 'Emma Wilson',
    username: 'emmaw',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    bio: 'Artist & Creative Director',
    followers: 23100,
    following: 567,
  },
  {
    id: '4',
    name: 'Marcus Johnson',
    username: 'marcusj',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    bio: 'Adventure seeker | Storyteller',
    followers: 15600,
    following: 321,
  },
  {
    id: '5',
    name: 'Olivia Parker',
    username: 'oliviap',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop',
    bio: 'Food blogger | Recipe creator',
    followers: 45200,
    following: 234,
  },
  {
    id: '6',
    name: 'David Kim',
    username: 'davidk',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    bio: 'Tech entrepreneur | Startup advisor',
    followers: 32100,
    following: 189,
  },
];

const generateComments = (postId: string, count: number): Comment[] => {
  const commentTexts = [
    'This is absolutely stunning! Love the composition.',
    'Where was this taken? I need to visit!',
    'Great capture! The lighting is perfect.',
    'This made my day better. Thank you for sharing!',
    'I\'ve been following your work for a while, this is one of your best!',
    'The colors in this are incredible.',
    'Can\'t wait to see more content like this!',
    'This speaks to my soul. Beautiful work.',
    'Wow! Just wow. Keep creating!',
    'Perfection in every pixel.',
  ];

  const shuffled = [...commentTexts].sort(() => Math.random() - 0.5);
  return Array.from({ length: count }, (_, i) => ({
    id: `${postId}-comment-${i}`,
    userId: users[Math.floor(Math.random() * users.length)].id,
    user: users[Math.floor(Math.random() * users.length)],
    content: shuffled[i % shuffled.length],
    createdAt: new Date(Date.now() - Math.random() * 86400000 * 2).toISOString(),
    likes: Math.floor(Math.random() * 50),
  }));
};

export const mockPosts: Post[] = [
  {
    id: '1',
    userId: '1',
    user: users[0],
    content: 'Golden hour at the mountains. There\'s something magical about watching the sun paint the peaks in shades of orange and gold. Nature never fails to amaze me.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
    comments: generateComments('1', 4),
    likes: 342,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    isFeatured: true,
  },
  {
    id: '2',
    userId: '2',
    user: users[1],
    content: 'Late night coding session with the perfect view. Sometimes the best ideas come when the world is quiet. Working on something exciting!',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=800&fit=crop',
    comments: generateComments('2', 3),
    likes: 189,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: '3',
    userId: '3',
    user: users[2],
    content: 'New artwork completed! This piece explores the intersection of nature and technology. What do you think?',
    image: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=1200&h=800&fit=crop',
    comments: generateComments('3', 6),
    likes: 567,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    isFeatured: true,
  },
  {
    id: '4',
    userId: '4',
    user: users[3],
    content: 'Road trip through the desert. Miles of open road and endless skies. This is freedom.',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&h=800&fit=crop',
    comments: generateComments('4', 2),
    likes: 234,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: '5',
    userId: '5',
    user: users[4],
    content: 'Sunday brunch perfection. Homemade avocado toast with poached eggs and a sprinkle of everything bagel seasoning. Recipe in bio!',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=1200&h=800&fit=crop',
    comments: generateComments('5', 5),
    likes: 423,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    isFeatured: true,
  },
  {
    id: '6',
    userId: '6',
    user: users[5],
    content: 'Building the future, one line of code at a time. Our startup just hit a major milestone! Grateful for the journey.',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=800&fit=crop',
    comments: generateComments('6', 7),
    likes: 312,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '7',
    userId: '1',
    user: users[0],
    content: 'Beach vibes and good times. Caught this moment during sunset and it took my breath away.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=800&fit=crop',
    comments: generateComments('7', 3),
    likes: 278,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: '8',
    userId: '3',
    user: users[2],
    content: 'Creative process in action. Sometimes the messiest studios produce the most beautiful work.',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1200&h=800&fit=crop',
    comments: generateComments('8', 4),
    likes: 156,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
];

export { users };
